from pathlib import Path
p=Path('/home/ubuntu/hoiku-note/client/src/pages/Home.tsx')
s=p.read_text()
# add slugs to the six topic objects by unique title context
pairs=[('label: "ハラスメント",','label: "ハラスメント",\n    slug: "pawahara-taisho",'),('label: "働き方",','label: "働き方",\n    slug: "yukyu-torenai",'),('label: "お金",','label: "お金",\n    slug: "tedori-20man",'),('label: "転職",','label: "転職",\n    slug: "nendo-tochu-tenshoku",'),('label: "ライフイベント",','label: "ライフイベント",\n    slug: "ninshin-taishoku-trouble",'),('label: "人間関係",','label: "人間関係",\n    slug: "ningen-kankei-tsukareta",')]
for a,b in pairs: s=s.replace(a,b,1)
s=s.replace('function scrollToId(id: string) {\n  document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" });\n}\n','''function scrollToId(id: string) {\n  document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" });\n}\n\nconst LINE_URL = "https://hoiku.proreach.co.jp/rl/instagram_aya-7sqz";\n\nfunction trackEvent(name: string, params: Record<string, string>) {\n  const gtag = (window as Window & { gtag?: (...args: unknown[]) => void }).gtag;\n  gtag?.("event", name, params);\n}\n''')
s=s.replace('  const [openFaq, setOpenFaq] = useState<number | null>(0);','''  const [openFaq, setOpenFaq] = useState<number | null>(0);\n  const [lineModal, setLineModal] = useState<{ position: "top" | "mid" | "bottom" } | null>(null);\n\n  const openLineModal = (position: "top" | "mid" | "bottom") => {\n    setLineModal({ position });\n    trackEvent("line_cta_click", { article: "home", position, step: "modal_open" });\n  };''')
s=s.replace('<a href="https://hoiku.proreach.co.jp/rl/instagram_aya-7sqz" target="_blank" rel="noreferrer" className="header-cta"><MessageCircle size={16} />無料相談</a>','<button onClick={() => openLineModal("top")} className="header-cta"><MessageCircle size={16} />無料相談</button>')
s=s.replace('''<button key={topic.title} className={`topic-card topic-${topic.tone}`} onClick={() => scrollToId("article")} style={{ animationDelay: `${index * 45}ms` }}>''','''<a key={topic.title} href={`/articles/${topic.slug}/`} className={`topic-card topic-${topic.tone}`} style={{ animationDelay: `${index * 45}ms` }}>''')
s=s.replace('''                  </button>\n                );''','''                  </a>\n                );''',1)
s=s.replace('<a href="https://hoiku.proreach.co.jp/rl/instagram_aya-7sqz" target="_blank" rel="noreferrer" className="aside-link">LINEで話を聞く <ArrowRight size={15} /></a>','<button onClick={() => openLineModal("mid")} className="aside-link">LINEで話を聞く <ArrowRight size={15} /></button>')
s=s.replace('<a className="line-button" href="https://hoiku.proreach.co.jp/rl/instagram_aya-7sqz" target="_blank" rel="noreferrer">LINEで無料相談する <ArrowRight size={17} /></a>','<button className="line-button" onClick={() => openLineModal("bottom")}>LINEで無料相談する <ArrowRight size={17} /></button>')
needle='''      <footer className="footer"><div className="container flex flex-col justify-between gap-5 py-8 sm:flex-row sm:items-center"><div><div className="footer-brand">保育ノート</div><p>保育士の悩みに寄り添う、仕事と暮らしのメディア</p></div><div className="footer-links"><button onClick={() => scrollToId("topics")}>悩みから探す</button><button onClick={() => scrollToId("about")}>運営について</button><span>© 2026 Hoiku Note</span></div></div></footer>'''
modal='''      <footer className="footer"><div className="container flex flex-col justify-between gap-5 py-8 sm:flex-row sm:items-center"><div><div className="footer-brand">保育ノート</div><p>保育士の悩みに寄り添う、仕事と暮らしのメディア</p></div><div className="footer-links"><button onClick={() => scrollToId("topics")}>悩みから探す</button><button onClick={() => scrollToId("about")}>運営について</button><span>© 2026 Hoiku Note</span></div></div></footer>\n      {lineModal && <div className="modal-backdrop" role="presentation" onClick={() => setLineModal(null)}><div className="line-modal" role="dialog" aria-modal="true" aria-labelledby="line-modal-title" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setLineModal(null)} aria-label="閉じる"><X size={18} /></button><div className="modal-icon"><MessageCircle size={22} /></div><span className="mini-kicker">LINE FREE CONSULTATION</span><h2 id="line-modal-title">相談内容は、まとまっていなくて大丈夫です。</h2><p>たとえば、こんなことから話せます。</p><ul><li>職場の人間関係やパワハラがつらい</li><li>有給・給与・転職のことを聞きたい</li><li>妊娠や退職について誰かに相談したい</li></ul><a className="line-button modal-button" href={LINE_URL} target="_blank" rel="noreferrer" onClick={() => trackEvent("line_cta_click", { article: "home", position: lineModal.position, step: "line_redirect" })}>LINEで無料相談をはじめる <ArrowRight size={17} /></a><small>外部のLINE相談ページへ移動します。無理な勧誘はありません。</small></div></div>}'''
if needle not in s: raise SystemExit('footer needle not found')
s=s.replace(needle,modal)
p.write_text(s)
print('patched Home.tsx')
''
